version: "3.9"
services:
  parser:
    image: endlessh-parser
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=postgres
      - DB_TABLE=endlessh
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - IPINFO_TOKEN=${IPINFO_TOKEN}
    depends_on:
      - timescaledb
    volumes:
      - ./endlessh.log:/endlessh.log
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/timescaledb:/var/lib/postgresql/dat