name: Build docker images

on:
  push:

jobs:
  build-docker:
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Explicitly set, even though this is default
          fetch-depth: 1
          # Explicitly set, even though this is default
          lfs: false
          # Explicitly set, even though this is default
          submodules: false
          clean: false
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/scarjit/endlessh-parser:latest